[ansadmin@ansible docker]$ cat  regapp-deployment-k8s.yml
---
- hosts: microk8s
  user: root
  #become: true


  tasks:
  - name: deploy regapp on k8s
    command: microk8s  kubectl apply -f regapp-deployment.yml

[ansadmin@ansible docker]$ cat regapp-sevice-k8s.yml
---
- hosts: microk8s
  user: root
  #become: true


  tasks:
  - name: deploy regapp on k8s
    command: microk8s  kubectl apply -f regapp-svc.yml


