apiVersion: v1
kind: Service
metadata:
  name: nixmsa-service
  labels:
    app: regapp      
spec:
  type: NodePort      
  selector:
    app: regapp
  ports:
      port: 8080
      targetPort: 8080
      nodePort: 30009
      
