---
- hosts: microk8s
  user: root
  #become: true


  tasks:

  - name: deploy regapp on k8s
    command: microk8s  kubectl apply -f regapp-deployment.yml

  - name: deploy service on K8s
    command: microk8s  kubectl apply -f regapp-svc.yml   

  - name: Rolling Update if image update in docker hub
    command: microk8s kubectl rollout restart deployment.apps/nixmsa-regapp  
